name: React App Deployment 

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:

      - name: Setup ssh keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'

          export NVM_DIR="/home/ubuntu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use v22.14.0

          node -v 
          npm -v 

          rm -rf /home/ubuntu/app
          mkdir -p /home/ubuntu/app
          cd /home/ubuntu/app

          git clone https://github.com/${{ github.repository }}.git .

          npm install 
          npm run build

          sudo mv /home/ubuntu/app/dist/* /var/www/html/
          sudo service nginx restart

          EOF